name: m2g code check
on:
  push:
    branches:
      - "deploy"
      - "main"
  pull_request:
  workflow_call:

jobs:
  code-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Run Format Check
        run: |
          pip install -U pip setuptools wheel black isort
          black --check --diff ./m2g
          isort --check-only --profile black ./m2g
